username: admin
timeout: 10s

common_arista_subscriptios: &common_arista_sub
  skip-verify: true
  password: admin
  encoding: json_ietf
  subscriptions:
    - eos_bgp_neighbors
    - eos_cpu
    - eos_mem
    - eos_interface_stats
    - show_ver

targets:
  eos1: 6030
    insecure: true
  eos2: 6030
    insecure: true

subscriptions:
  eos_bgp_neighbors:
    paths:
      - /network-instances/network-instance[name=default]/protocols/protocol[name=BGP]/bgp/neighbors
    mode: stream
    stream-mode: on_change
    sample-interval: 5s

  eos_cpu:
    paths:
      - components/component/cpu
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  eos_mem:
    paths:
      - components/component/state/memory/
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  eos_interface_stats:
    paths:
      - /interfaces/interface[name=*]/state/counters
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  show_ver:
    paths:
      - eos_native:/Eos/image
    mode: stream
    stream-mode: sample
    sample-interval: 60s

outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - up-down-map
  # stdout:
  #   type: file
  #   file-type: stdout
  #   event-processors:
  #     - proc-convert-strings-to-int
  #     - trim-prefixes

processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  up-down-map:
    event-strings:
      value-names:
        - oper-state
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
